sudo: required

dist: xenial  # needed for more recent python 3 and python3-venv

language: generic

stages:
  - lint
  - test

services:
  - docker

before_install:
  - travis_retry sudo apt update -qq
  # to successfully send the coveralls reports we need pyOpenSSL
  - travis_retry sudo apt install -qq --no-install-recommends
    python2.7 python3 python3-venv python3-virtualenv python3-pip
    python3-setuptools python3-openssl
  # (venv/virtualenv are both used by tests/test_pythonpackage.py)
  - sudo pip install tox>=2.0
  - sudo pip3 install coveralls
  # https://github.com/travis-ci/travis-ci/issues/6069#issuecomment-266546552
  - git remote set-branches --add origin master
  - git fetch

env:
  global:
    - ANDROID_SDK_HOME=/opt/android/android-sdk
    - ANDROID_NDK_HOME=/opt/android/android-ndk

jobs:
  include:
    - stage: lint
      name: "Tox tests and coverage"
      script:
        # we want to fail fast on tox errors without having to `docker build` first
        - tox -- tests/ --ignore tests/test_pythonpackage.py
        # (we ignore test_pythonpackage.py since these run way too long!!
        #  test_pythonpackage_basic.py will still be run.)
      after_success:
        - coveralls

    - &testing
      stage: test
      before_script:
        # build docker image
        - docker build --tag=p4a --file Dockerfile.py3 .
        # Run a background process to make sure that travis will not kill our tests in
        # case that the travis log doesn't produce any output for more than 10 minutes
        - while sleep 540; do echo "==== Still running (travis, don't kill me) ===="; done &
      script:
        - docker run -e CI -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" p4a /bin/sh -c "$COMMAND"
      after_script:
        # kill the background process started before run docker
        - kill %1
      name: Python 3 basic
      # overrides requirements to skip `peewee` pure python module, see:
      # https://github.com/kivy/python-for-android/issues/1263#issuecomment-390421054
      env: COMMAND='. venv/bin/activate && cd testapps/ && python setup_testapp_python3_sqlite_openssl.py apk --sdk-dir $ANDROID_SDK_HOME --ndk-dir $ANDROID_NDK_HOME --requirements libffi,sdl2,pyjnius,kivy,python3,openssl,requests,sqlite3,setuptools'
    - <<: *testing
      name: Python 2 basic
      env: COMMAND='. venv/bin/activate && cd testapps/ && python setup_testapp_python2_sqlite_openssl.py apk --sdk-dir $ANDROID_SDK_HOME --ndk-dir $ANDROID_NDK_HOME --requirements sdl2,pyjnius,kivy,python2,openssl,requests,sqlite3,setuptools'
    - <<: *testing
      name: Python 2 numpy
      env: COMMAND='. venv/bin/activate && cd testapps/ && python setup_testapp_python2.py apk --sdk-dir $ANDROID_SDK_HOME --ndk-dir $ANDROID_NDK_HOME --bootstrap sdl2 --requirements python2,numpy'
    - <<: *testing
      name: Rebuild updated recipes
      env: COMMAND='. venv/bin/activate && ./ci/rebuild_updated_recipes.py'
